# Generated by Django 5.1.5 on 2026-02-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0008_alter_accommodationrequest_furnishing_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property'),
        ),
    ]
