# Generated by Django 5.1.5 on 2026-02-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on home page'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified tenant who actually rented'),
        ),
        migrations.AddField(
            model_name='review',
            name='landlord_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['landlord', '-created_at'], name='accounts_re_landlor_a9eecb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', '-created_at'], name='accounts_re_rating_ee0786_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_featured', '-created_at'], name='accounts_re_is_feat_7dbc71_idx'),
        ),
    ]
