# Generated by Django 5.1.5 on 2026-02-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
    ]
