# Generated by Django 5.1.5 on 2026-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_disabled_access_property_pets_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
