# Generated by Django 5.1.5 on 2026-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Room'), ('double', 'Double Room'), ('ensuite', 'Ensuite Room'), ('semi_double', 'Semi-Double Room')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('whole', 'Whole Property'), ('room', 'Room')], max_length=20),
        ),
    ]
