# Generated by Django 5.1.5 on 2026-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_room_type_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationrequest',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('whole', 'Whole Property'), ('room', 'Room')], max_length=20),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='searching_for',
            field=models.CharField(choices=[('just_me', 'Just me'), ('me_and_partner', 'Me and a partner'), ('me_and_friend', 'Me and a friend')], default='just_me', max_length=20),
        ),
    ]
