# Generated by Django 5.1.5 on 2026-02-21 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_accommodationrequest_accommodation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationrequest',
            name='budget_range',
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Room'), ('double', 'Double Room'), ('ensuite', 'Ensuite Room'), ('semi_double', 'Semi-Double Room')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accommodationrequest',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodationrequest',
            name='bedrooms_needed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='accommodationrequest',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
