# Generated by Django 5.1.5 on 2026-02-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_accommodationrequest_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationrequest',
            name='disabled_access_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='garden_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='parking_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='pets_allowed_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='wifi_required',
            field=models.BooleanField(default=False),
        ),
    ]
