# Generated by Django 5.1.5 on 2026-02-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_accommodationrequest_disabled_access_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationrequest',
            name='furnishing_preference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
