# Generated by Django 5.1.5 on 2026-02-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationrequest',
            name='additional_requirements',
            field=models.TextField(blank=True, help_text='Any additional requirements or preferences'),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='interested_in_buddy_up',
            field=models.BooleanField(default=False, help_text='Interested in finding roommates to share accommodation'),
        ),
    ]
