# Generated by Django 5.1.5 on 2026-02-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('bid_received', 'Bid Received'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_countered', 'Bid Countered'), ('message', 'Message'), ('message_received', 'Message Received'), ('payment_received', 'Payment Received'), ('payment_released', 'Payment Released'), ('contract_generated', 'Contract Generated'), ('contract_signed', 'Contract Signed'), ('contract_expiring', 'Contract Expiring'), ('contract_expired', 'Contract Expired'), ('renewal_requested', 'Renewal Requested'), ('property_saved', 'Property Saved'), ('review', 'Review'), ('review_received', 'Review Received')], max_length=30),
        ),
    ]
